# -*- coding: utf-8 -*-
"""Day-4-python-and-machine-learning

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FDI9gFGv9lkpwTVPKL4H-4LaHezTE0jO
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

# ------------------------------------------
# Load Dataset
# ------------------------------------------

housing = fetch_california_housing(as_frame=True)
df = housing.frame

print("=" * 50)
print("First Five Rows")
print("=" * 50)
print(df.head())

print("=" * 50)
print("Dataset Info")
print("=" * 50)
print(df.info())

print("=" * 50)
print("Statistical Summary")
print("=" * 50)
print(df.describe())

print("=" * 50)
print("Missing Values")
print("=" * 50)
print(df.isnull().sum())

# ------------------------------------------
# Input and Target
# ------------------------------------------

X = df.drop("MedHouseVal", axis=1)
y = df["MedHouseVal"]

# ------------------------------------------
# Split Dataset
# ------------------------------------------

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("\nTraining Shape:", X_train.shape)
print("Testing Shape :", X_test.shape)

# ------------------------------------------
# Train Model
# ------------------------------------------

model = LinearRegression()

model.fit(X_train, y_train)

print("\nModel Training Completed")

# ------------------------------------------
# Prediction
# ------------------------------------------

y_pred = model.predict(X_test)

comparison = pd.DataFrame({
    "Actual": y_test.values,
    "Predicted": y_pred
})

print(comparison.head())

# ------------------------------------------
# Evaluation
# ------------------------------------------

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

print("\nEvaluation Metrics")
print("-" * 40)
print("MAE :", mae)
print("MSE :", mse)
print("RMSE :", rmse)
print("R2 Score :", r2)

# ------------------------------------------
# Coefficients
# ------------------------------------------

coef = pd.DataFrame({
    "Feature": X.columns,
    "Coefficient": model.coef_
})

print("\nFeature Importance")
print(coef)

# ------------------------------------------
# Actual vs Predicted Plot
# ------------------------------------------

plt.figure(figsize=(8,6))

plt.scatter(y_test, y_pred)

plt.xlabel("Actual House Price")

plt.ylabel("Predicted House Price")

plt.title("Actual vs Predicted")

plt.grid(True)

plt.show()

# ------------------------------------------
# Residual Plot
# ------------------------------------------

residuals = y_test - y_pred

plt.figure(figsize=(8,6))

plt.scatter(y_pred, residuals)

plt.axhline(y=0,color='red')

plt.xlabel("Predicted")

plt.ylabel("Residual")

plt.title("Residual Plot")

plt.grid(True)

plt.show()

# ------------------------------------------
# New Prediction
# ------------------------------------------

new_house = [[
    8.5,
    20,
    6,
    1011,
    900,
    3,
    34,
    -118
]]

prediction = model.predict(new_house)

print("\nPredicted House Value :", prediction[0])